config/routes.rb
Mbuilder::Application.routes.draw do
  mount InsteddTelemetry::Engine => '/instedd_telemetry'

  get "logs/index"

  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks', sessions: 'sessions'}
  guisso_for :user

  resources :applications do
    resources :channels
    resources :message_triggers
    resources :periodic_tasks
    resources :validation_triggers
    resources :external_triggers
    resources :messages, only: :create
    resources :logs, only: :index
    resources :contacts, only: [:index, :show]

    resources :external_services, except: [:show, :edit, :new] do
      member do
        put :update_manifest
      end
    end

    get :data
    resources :tables, only: [] do
      resources :records, except: [:index, :show]
      collection do
        post :upload
        post :import
      end
    end

    get :export
    post :import

    get :request_api_token
  end

  get '/api/applications' => 'api#applications'
  get '/api/applications/:id/actions' => 'api#actions', as: :application_actions
  get '/api/applications/:id/tables' => 'api#index',as: :api_index
  get '/api/applications/:id/tables/:table_id(.:format)' => 'api#show', as: :api_show, defaults: { format: 'json' }

  post '/external/application/:application_id/trigger/:trigger_name(.:format)' => 'external_triggers#run', as: :run_external_trigger, defaults: { format: 'json' }

  authenticate :user do
    mount Pigeon::Engine => '/pigeon'
  end

  match '/nuntium/receive_at' => 'nuntium#receive_at'

  match '/resource_map/collections.json' => 'resource_map#collections'
  match '/resource_map/collections/:id/fields.json' => 'resource_map#collection_fields'
  match '/hub/*path' => 'hub#api', format: false

  mount Listings::Engine => '/listings'

  root :to => 'home#index'
end

app/models/application.rb
class Application < ActiveRecord::Base
  attr_accessible :name, :user_id, :time_zone

  belongs_to :user
  has_many :message_triggers, dependent: :destroy
  has_many :external_triggers, dependent: :destroy
  has_many :periodic_tasks, dependent: :destroy
  has_many :validation_triggers, dependent: :destroy
  has_many :channels, dependent: :destroy
  has_many :logs, class_name: :ExecutionLogger, dependent: :destroy
  has_many :external_services, dependent: :destroy
  has_many :external_service_steps, :through => :external_services
  has_many :contacts, dependent: :destroy

  validates_presence_of :user, :name, :time_zone

  after_save :create_index
  after_save :touch_lifespan
  after_destroy :touch_lifespan
  before_destroy :delete_local_index

  serialize :tables

  def tz
    ActiveSupport::TimeZone.new(self.time_zone)
  end

  def accept_message(message)
    Executor.new(self).execute(message)
  end

  def simulate_triggers_execution
    simulate_execution_of message_triggers
  end

  def simulate_execution_of triggers
    context = MemoryExecutionContext.new self, TriggerPlaceholderSolver.new, ExecutionLogger.new(application: self)
    context.execute_many triggers
  end

  def simulate_triggers_execution_excluding trigger
    simulate_execution_of(message_triggers - [trigger])
  end

  def find_external_service_step(guid)
    external_service_steps.includes(:external_service).find_by_guid(guid)
  end

  def find_table(guid)
    table = tables.find { |table| table.guid == guid }
    raise ActiveRecord::RecordNotFound.new("There is no table with id \"#{guid}\"") unless table
    table
  end

  def find_table_by_name(name)
    tables.find { |table| table.name == name }
  end

  def local_index(create_if_not_exists = true)
    index = LocalIndex.new(local_index_name)
    if create_if_not_exists && !index.exists?
      index.create(settings: {
        index: {
          analysis: {
            analyzer: {
              default: {
                tokenizer: :keyword,
                filter: [:lowercase],
                type: :custom,
              }
            }
          }
        }
      })
    end
    index
  end

  def delete_local_index
    local_index.delete
  end

  def create_index
    local_index(true)
  end

  def local_search(table)
    LocalSearch.new local_index, table
  end

  def rebind_tables_and_fields(table_and_field_rebinds)
    all_triggers = message_triggers.all + validation_triggers.all + periodic_tasks.all

    table_and_field_rebinds.each do |rebind|
      case rebind['kind']
      when 'table'
        from_table = rebind['fromTable']
        to_table = rebind['toTable']
        all_triggers.each { |trigger| trigger.rebind_table from_table, to_table }
      when 'field'
        from_field = rebind['fromField']
        to_table = table_of(rebind['toField']).guid
        to_field = rebind['toField']
        all_triggers.each { |trigger| trigger.rebind_field from_field, to_table, to_field }
      end
    end

    all_triggers.each(&:save!)
  end

  def table_of field_guid
    tables.detect(proc{raise "Table not found for #{field_guid} #{tables}"}) do |table|
      table.fields.any? do |field|
        field.guid == field_guid
      end
    end
  end

  def export file
    data = {
      tables: tables,
      message_triggers: message_triggers,
      periodic_tasks: periodic_tasks,
      validation_triggers: validation_triggers,
      external_triggers: external_triggers,
      external_services: external_services.map(&:export)
    }

    file.write data.to_json_oj
  end

  def import! file
    data = JSON.load file

    self.tables = Table.from_list(data["tables"])
    self.message_triggers = MessageTrigger.from_list(data["message_triggers"])
    self.periodic_tasks = PeriodicTask.from_list(data["periodic_tasks"])
    self.validation_triggers = ValidationTrigger.from_list(data["validation_triggers"])
    self.external_triggers = ExternalTrigger.from_list(data["external_triggers"])
    self.external_services = ExternalService.from_list(data["external_services"])

    save!
  end

  def local_tables
    (self.tables || []).select {|table| table.is_a? Tables::Local }
  end

  def elastic_record_for(table)
    ElasticRecord.for(self.local_index.name, table.guid)
  end

  def rebuild_local_tables
    data = {}
    local_tables.each do |table|
      record_class = elastic_record_for(table)
      data[table.guid] = record_class.all.map(&:as_json)
    end

    self.delete_local_index

    local_tables.each do |table|
      # ElasticRecord clases are not catched since index is recreated
      record_class = elastic_record_for(table)
      record_class.create data[table.guid]
    end
  end

  def touch_lifespan
    Telemetry::Lifespan.touch_application(self)
  end

  if Rails.env.test?
    def local_index_name
      "mbuilder_test_application_#{id}"
    end
  else
    def local_index_name
      "mbuilder_application_#{id}"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def render_json(object, params={})
    render params.merge(text: object.to_json_oj, content_type: 'text/json')
  end

  def self.set_application_tab(key)
    before_filter do
      send :set_application_tab, key
    end
  end

  def set_application_tab(key)
    @application_tab = key
  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  layout "applications", except: [:index, :new]
  layout "application", only: [:index, :new]
  add_breadcrumb 'Applications', :applications_path

  before_filter :authenticate_user!

  expose(:applications) { current_user.applications }
  expose(:application)

  def show
    add_breadcrumb application.name, application
    add_breadcrumb 'Overview'
    set_application_tab :overview

    @message_count_all = application.logs.count
    @message_count_today = application.logs.where('created_at >= ?', Date.today).count
    @message_count_7_days = application.logs.where('created_at >= ?', 7.days.ago).count
    @message_count_30_days = application.logs.where('created_at >= ?', 30.days.ago).count
  end

  def new
    add_breadcrumb 'New application'
    set_application_tab :new
  end

  def create
    if application.save
      redirect_to application
    else
      render :new
    end
  end

  def edit
    add_breadcrumb application.name, application
    add_breadcrumb 'Settings'
    set_application_tab :settings
  end

  def update
    if application.update_attributes(params[:application])
      redirect_to application
    else
      render :edit
    end
  end

  def destroy
    application.destroy
    redirect_to applications_path
  end

  def data
    add_breadcrumb application.name, application
    add_breadcrumb 'Data'
    set_application_tab :data

    @data = application.local_tables
  end

  def export
    filename = "#{application.name}-#{application.id}-#{application.updated_at.strftime("%F")}.mba"
    file = Tempfile.new filename
    begin
      application.export file
    ensure
      file.close
    end
    send_file file.path, filename: filename
  end

  def import
    begin
      application.import! File.read(params[:mba].tempfile.path)
      flash.notice = 'Application imported'
      redirect_to application
    rescue
      flash.alert = 'Error importing application'
      redirect_to application
    end
  end

  def request_api_token
    @token = Guisso.generate_bearer_token current_user.email
    @url_params = { access_token: @token }
    render layout: false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link(url)
    link_to url, url
  end
end

app/views/applications/_form.haml
= form_for application do |f|
  - if application.errors.present?
    .alert-container
      .alert.alert-error
        %ul
          - application.errors.full_messages.each do |msg|
            %li= msg

  %div
    = f.label :name
    = f.text_field :name, autofocus: true
  %div
    = f.label :time_zone
    = f.time_zone_select :time_zone
    %span.help-block
      This will be used for displaying and setting up dates and times, for example when scheduling a recurrent action.

  = f.submit class: 'btn'

app/views/applications/data.haml
- @data.each do |table|
  %h4{style: 'display: inline-block'}=table.name

  %div
    = icon_link_to 'icf-add', "Add new record", new_application_table_record_path(application.id, table.guid)

    .table-import-collapsible
      - collapsible_form_for upload_application_tables_path(application, table_guid: table.guid), icon: 'import', title: 'Import CSV', description: 'Select a CSV file to import data from', submit: 'Import', id: "import-table-#{table.guid}" do |f|
        %input#choose-file{:disabled => "disabled", :placeholder => "Choose File"}/
        .file-upload
          = icon_link_to :'icf-arrow', 'Choose a file', '#'
          = file_field_tag 'file', class: 'choose'
    %br
    %br

    = render_listing "es__#{application.id}__#{application.local_index_name}__#{table.guid}".to_sym

  %hr

-# = link_to "Create from CSV", import_application_tables_path(application.id), class: 'btn btn-default'

- collapsible_form_for upload_application_tables_path(application), icon: 'import', title: 'Create new from CSV', description: 'Select a CSV file to import data from', submit: 'Import', id: 'import-new-table' do |f|
  %input#choose-file{:disabled => "disabled", :placeholder => "Choose File"}/
  .file-upload
    = icon_link_to :'icf-arrow', 'Choose a file', '#'
    = file_field_tag 'file', class: 'choose'

app/views/applications/edit.haml
%p
  Get access through API.
  = link_to 'Request API token', application_request_api_token_path(application),
    data: { toggle: 'modal', target: '#api-modal' }

#api-modal.modal.hide.fade(tabindex="-1" role="dialog")
  .modal-header
    %button.close(type="button" class="close" data-dismiss="modal") ×
    %h3 API access
  .modal-body
    Loading ...
  .modal-footer
    %button.btn(data-dismiss="modal") Close

= render 'form'

app/views/applications/index.haml
.row-fluid
  .span12
    .title Applications

.row-fluid
  .span6
    - simple_list :application, title: 'My Applications', icon: :folder, create_path: new_application_path do
      - applications.each do |application|
        - simple_list_item application.name, application

app/views/applications/new.haml
%h3 New Application

= render 'form'

app/views/applications/request_api_token.haml
Access Token
%pre= @token

.warning
  Save this token. You con revoke it at
  = link_to Guisso.admin_tokens_url, Guisso.admin_tokens_url, target: '_blank'

%dl
  %dt
    Tables index
  %dd
    = link api_index_url(application.id, @url_params)

  - application.local_tables.each do |table|
    %dt
      = table.name
    %dd
      json:
      = link api_show_url(application.id, table.name, @url_params.merge(format: :json))
    %dd
      csv:
      = link api_show_url(application.id, table.name, @url_params.merge(format: :csv))

app/views/applications/show.haml
.row-fluid
  .span12
    %h4 Messages
    %p.small Total number of messages sent and received
    .messages-box
      %h1
        = number_with_delimiter @message_count_all
        %small messages received

      %p
        = number_with_delimiter @message_count_today
        from today
      %p
        = number_with_delimiter @message_count_7_days
        from last 7 days
      %p
        = number_with_delimiter @message_count_30_days
        from last 30 days

.row-fluid
  .span12
    .span3
      = icon_link_to :'icf-export', 'Export application', application_export_path(application)

    .span9
      - collapsible_form_for application_import_path(application), icon: 'import', title: 'Import application', description: 'Upload an .mba in order to import an application', submit: 'Import', id: 'import-form' do |f|
        %input#choose-file{:disabled => "disabled", :placeholder => "Choose File"}/
        .file-upload
          = icon_link_to :'icf-arrow', 'Choose a file', '#'
          = file_field_tag 'mba', class: 'choose'

%hr

= icon_link_to :'icf-delete', "Delete this application", application, method: :delete, confirm: "Are you sure you want to delete the application '#{application.name}'"