config/routes.rb
Mbuilder::Application.routes.draw do
  mount InsteddTelemetry::Engine => '/instedd_telemetry'

  get "logs/index"

  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks', sessions: 'sessions'}
  guisso_for :user

  resources :applications do
    resources :channels
    resources :message_triggers
    resources :periodic_tasks
    resources :validation_triggers
    resources :external_triggers
    resources :messages, only: :create
    resources :logs, only: :index
    resources :contacts, only: [:index, :show]

    resources :external_services, except: [:show, :edit, :new] do
      member do
        put :update_manifest
      end
    end

    get :data
    resources :tables, only: [] do
      resources :records, except: [:index, :show]
      collection do
        post :upload
        post :import
      end
    end

    get :export
    post :import

    get :request_api_token
  end

  get '/api/applications' => 'api#applications'
  get '/api/applications/:id/actions' => 'api#actions', as: :application_actions
  get '/api/applications/:id/tables' => 'api#index',as: :api_index
  get '/api/applications/:id/tables/:table_id(.:format)' => 'api#show', as: :api_show, defaults: { format: 'json' }

  post '/external/application/:application_id/trigger/:trigger_name(.:format)' => 'external_triggers#run', as: :run_external_trigger, defaults: { format: 'json' }

  authenticate :user do
    mount Pigeon::Engine => '/pigeon'
  end

  match '/nuntium/receive_at' => 'nuntium#receive_at'

  match '/resource_map/collections.json' => 'resource_map#collections'
  match '/resource_map/collections/:id/fields.json' => 'resource_map#collection_fields'
  match '/hub/*path' => 'hub#api', format: false

  mount Listings::Engine => '/listings'

  root :to => 'home#index'
end

app/views/shared/_application_tabs.haml
.title= application.name

%ul.nav.nav-tabs
  %li{class: @application_tab == :overview ? 'active' : nil}
    = link_to "Overview", application
  %li{class: @application_tab == :triggers ? 'active' : nil}
    = link_to "Triggers", application_message_triggers_path(application)
  %li{class: @application_tab == :external_services ? 'active' : nil}
    = link_to "External Services", application_external_services_path(application)
  %li{class: @application_tab == :recent_activity ? 'active' : nil}
    = link_to "Recent Activity", application_logs_path(application)
  %li{class: @application_tab == :address_book ? 'active' : nil}
    = link_to "Address Book", application_contacts_path(application)
  %li{class: @application_tab == :channels ? 'active' : nil}
    = link_to "Channels", application_channels_path(application)
  %li{class: @application_tab == :data ? 'active' : nil}
    = link_to "Data", application_data_path(application)
  %li{class: @application_tab == :settings ? 'active' : nil}
    = link_to "Settings", edit_application_path(application)

app/views/shared/_field.haml
.pill-container
  .pill.field-ref{'ng-show' => 'fieldExists(action.field)', 'data-tooltip-content' =>'{{lookupFieldName(action.field)}}', 'ng-class' => '{ellipsis: (lookupFieldName(action.field).length > 20)}'}
    {{lookupFieldName(action.field)}}
  .pill.unbound{'ng-hide' => 'fieldExists(action.field)', 'dragover' => 'dragOverUnboundField(action.field, $event)', 'drop' => 'dropOverUnboundField(action.field, $event)'}
    ???

app/views/shared/_pill.haml
%span{'ng-repeat' => 'pill in [action.pill]'}
  %span(ng-include src='pillTemplateFor(pill)')

app/views/shared/_table.haml
.pill-container
  %span.pill.table-ref{'ng-show' => 'tableExists(action.table)', 'dragover' => 'dragOverUnboundTable(action.table, $event)', 'drop' => 'dropOverUnboundTable(action, action.table, $event)', 'dragenter' => 'dragEnterPlaceholder($event)', 'dragleave' => 'dragLeavePlaceholder($event)', 'data-tooltip-content' =>'{{lookupTableName(action.table)}}', 'ng-class' => '{ellipsis: (lookupTableName(action.table).length > 20)}'}
    {{lookupTableName(action.table)}}
  .pill.new.table-ref{'ng-hide' => 'tableExists(action.table)', 'dragover' => 'dragOverUnboundTable(action.table, $event)', 'drop' => 'dropOverUnboundTable(action, action.table, $event)', 'dragenter' => 'dragEnterPlaceholder($event)', 'dragleave' => 'dragLeavePlaceholder($event)'}
    define table

app/views/shared/_testing_sandbox.haml
.testing-sandbox{'ng-controller' => 'MessagesController', 'ng-init' => "applicationId=#{application.id}"}
  .sandbox-header
    %h4 Testing Sandbox
    %small Send messages to test your triggers
    %hr.shadow
  .sandbox-content
    .control-group
      %label{for: :from} From
      .controls
        %input.span12{'ng-model' => 'from', type: :text, name: :from}

    .control-group
      %label{for: :body} Message
      .controls
        %textarea.span12{'ng-model' => 'body', :rows => 5}
    %button.btn.btn-small.btn-warning{'ng-click' => 'send()'} Send

    %div{'ng-show' => 'loading'}
      %hr
      %label Loading ...

    %div{'ng-show' => 'actions.length'}
      %hr
      %label Performed actions
      %ul.p-actions
        %li{'ng-repeat' => 'action in actions', 'class' => "{{action.kind}}" }
          %i
          {{action.text}}