config/routes.rb
Mbuilder::Application.routes.draw do
  mount InsteddTelemetry::Engine => '/instedd_telemetry'

  get "logs/index"

  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks', sessions: 'sessions'}
  guisso_for :user

  resources :applications do
    resources :channels
    resources :message_triggers
    resources :periodic_tasks
    resources :validation_triggers
    resources :external_triggers
    resources :messages, only: :create
    resources :logs, only: :index
    resources :contacts, only: [:index, :show]

    resources :external_services, except: [:show, :edit, :new] do
      member do
        put :update_manifest
      end
    end

    get :data
    resources :tables, only: [] do
      resources :records, except: [:index, :show]
      collection do
        post :upload
        post :import
      end
    end

    get :export
    post :import

    get :request_api_token
  end

  get '/api/applications' => 'api#applications'
  get '/api/applications/:id/actions' => 'api#actions', as: :application_actions
  get '/api/applications/:id/tables' => 'api#index',as: :api_index
  get '/api/applications/:id/tables/:table_id(.:format)' => 'api#show', as: :api_show, defaults: { format: 'json' }

  post '/external/application/:application_id/trigger/:trigger_name(.:format)' => 'external_triggers#run', as: :run_external_trigger, defaults: { format: 'json' }

  authenticate :user do
    mount Pigeon::Engine => '/pigeon'
  end

  match '/nuntium/receive_at' => 'nuntium#receive_at'

  match '/resource_map/collections.json' => 'resource_map#collections'
  match '/resource_map/collections/:id/fields.json' => 'resource_map#collection_fields'
  match '/hub/*path' => 'hub#api', format: false

  mount Listings::Engine => '/listings'

  root :to => 'home#index'
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  expose(:application)
  expose(:application_table) { application.find_table(params[:table_id]) }
  expose(:record_class) { ElasticRecord.for(application.local_index.name, params[:table_id]) }
  expose(:record) do
    if params[:action] == "new" || params[:action] == "create"
      record_class.new params[:record].to_f_if_looks_like_number
    else
      record_class.find(params[:id])
    end
  end

  add_breadcrumb 'Applications', :applications_path


  def edit
    add_breadcrumb application.name, application
    add_breadcrumb 'Data', :application_data
    add_breadcrumb 'Edit record'

    render 'form'
  end

  def new
    add_breadcrumb application.name, application
    add_breadcrumb 'Data', :application_data
    add_breadcrumb 'New record'

    render 'form'
  end

  def update
    add_breadcrumb application.name, application
    add_breadcrumb 'Data', :application_data
    add_breadcrumb 'Edit record'

    if record.update_attributes params[:record].to_f_if_looks_like_number
      redirect_to controller: :applications, action: :data
    else
      flash.now[:alert] = "Record can't be saved"
      render 'form'
    end
  end

  def create
    add_breadcrumb application.name, application
    add_breadcrumb 'Data', :application_data
    add_breadcrumb 'New record'

    if record.save
      redirect_to controller: :applications, action: :data
    else
      flash.now[:alert] = "Record can't be saved"
      render 'form'
    end
  end

  def destroy
    @application_tab = :data
    record.destroy
    redirect_to controller: :applications, action: :data
  end
end

app/views/records/edit.haml
= render 'shared/application_tabs'

%h4= application_table.name

= form_for record, as: :record, url: application_table_record_path(application.id, application_table.guid, record.id) do |f|

  - application_table.fields.each do |field|
    .control-group
      %label.control-label{for: field.guid}= field.name
      .controls
        %input{type: 'text', name: "#{f.options[:as]}[#{field.guid}]", value: record.properties[field.guid]}

  = f.submit class: 'btn btn-primary'

app/views/records/form.haml
%h4= application_table.name

= form_for record, as: :record, url: (record.persisted? ? application_table_record_path(application.id, application_table.guid, record.id) : application_table_records_path(application.id, application_table.guid)) do |f|

  - application_table.fields.each do |field|
    .control-group{class: "#{'error' if record.errors.has_key?(field.guid.to_sym)}"}
      %label.control-label{for: field.guid}= field.name
      .controls
        %input.error{type: 'text', name: "#{f.options[:as]}[#{field.guid}]", value: record.properties[field.guid].try(:user_friendly)}
        - if record.errors.has_key?(field.guid.to_sym)
          %span.help-inline
            = record.errors.get(field.guid.to_sym).join(', ')

  - if record.persisted?
    = f.submit 'Update Record', class: 'btn btn-primary'
  - else
    = f.submit 'Create Record', class: 'btn btn-primary'