config/routes.rb
Mbuilder::Application.routes.draw do
  mount InsteddTelemetry::Engine => '/instedd_telemetry'

  get "logs/index"

  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks', sessions: 'sessions'}
  guisso_for :user

  resources :applications do
    resources :channels
    resources :message_triggers
    resources :periodic_tasks
    resources :validation_triggers
    resources :external_triggers
    resources :messages, only: :create
    resources :logs, only: :index
    resources :contacts, only: [:index, :show]

    resources :external_services, except: [:show, :edit, :new] do
      member do
        put :update_manifest
      end
    end

    get :data
    resources :tables, only: [] do
      resources :records, except: [:index, :show]
      collection do
        post :upload
        post :import
      end
    end

    get :export
    post :import

    get :request_api_token
  end

  get '/api/applications' => 'api#applications'
  get '/api/applications/:id/actions' => 'api#actions', as: :application_actions
  get '/api/applications/:id/tables' => 'api#index',as: :api_index
  get '/api/applications/:id/tables/:table_id(.:format)' => 'api#show', as: :api_show, defaults: { format: 'json' }

  post '/external/application/:application_id/trigger/:trigger_name(.:format)' => 'external_triggers#run', as: :run_external_trigger, defaults: { format: 'json' }

  authenticate :user do
    mount Pigeon::Engine => '/pigeon'
  end

  match '/nuntium/receive_at' => 'nuntium#receive_at'

  match '/resource_map/collections.json' => 'resource_map#collections'
  match '/resource_map/collections/:id/fields.json' => 'resource_map#collection_fields'
  match '/hub/*path' => 'hub#api', format: false

  mount Listings::Engine => '/listings'

  root :to => 'home#index'
end

app/models/message_trigger.rb
class MessageTrigger < Trigger
  attr_accessible :name, :message, :actions, :enabled

  belongs_to :application

  validates_presence_of :application, :name

  serialize :message
  serialize :actions

  generate_equals :name, :message, :actions

  scope :enabled, -> { where(enabled: true) }

  after_save :touch_application_lifespan
  after_destroy :touch_application_lifespan

  def self.from_hash(hash)
    new name: hash["name"], enabled: hash["enabled"], message: Message.from_hash(hash["message"]), actions: Action.from_list(hash["actions"])
  end

  def as_json
    {
      name: name,
      enabled: enabled,
      message: message,
      kind: kind,
      actions: actions.map(&:as_json)
    }
  end

  def default_from_number
    "+1-(234)-567-8912"
  end

  def match incoming_message
    message.match incoming_message
  end
end

app/controllers/message_triggers_controller.rb
class MessageTriggersController < MbuilderApplicationController
  before_filter do
    add_breadcrumb 'Triggers', application_message_triggers_path(application)
  end
  layout "trigger_edit"
  set_application_tab :triggers

  expose(:message_triggers) { application.message_triggers }
  expose(:message_trigger)
  expose(:periodic_tasks) { application.periodic_tasks }
  expose(:external_triggers) { application.external_triggers }

  expose(:validation_triggers) do
    validation_triggers = application.validation_triggers.all
    validation_triggers.each { |t| t.application = application }
    validation_triggers
  end

  def index
    render layout: "applications"
  end

  def create
    set_message_trigger_data(message_trigger)
  end

  def edit
    add_breadcrumb message_trigger.name, application_message_trigger_path(application, message_trigger)
  end

  def update
    set_message_trigger_data(message_trigger)
  end

  def destroy
    message_trigger.destroy
    redirect_to application_message_triggers_path(application)
  end

  def new
    add_breadcrumb 'New message trigger'
  end

  private

  def set_message_trigger_data(trigger)
    data = JSON.parse request.raw_post

    trigger.name = data['name']
    trigger.enabled = data['enabled']
    trigger.message = Message.from_hash(data['message'])
    trigger.actions = Action.from_list(data['actions'])

    application.tables = Table.from_list data['tables']

    begin
      ActiveRecord::Base.transaction do
        application.save!
        trigger.save!

        if data['tableAndFieldRebinds']
          application.rebind_tables_and_fields(data['tableAndFieldRebinds'])
        end
      end
      render_json trigger.id
    rescue ActiveRecord::RecordInvalid
      render_json trigger.errors.full_messages.join("\n"), status: 402
    end
  end
end

app/helpers/message_triggers_helper.rb
module MessageTriggersHelper
  def message_trigger_to_angular(application, trigger)
    str = ""
    str << "applicationId=#{trigger.application_id.to_json};"
    str << "id=#{trigger.id.to_json_oj};"
    str << "name=#{trigger.name.to_json_oj};"
    str << "enabled=#{trigger.enabled.to_json_oj};"

    if trigger.message
      from = trigger.message.from
      from = trigger.default_from_number if from.blank?

      # We add an empty text pill at the end so the user can place the cursor there
      pieces = (trigger.message.pieces + [MessagePiece.new("text", "", Guid.new.to_s)]).map(&:as_json).to_json_oj

      str << "from=#{from.to_json_oj};"
      str << "pieces=#{pieces};"
      str << "actions=#{trigger.actions.map(&:as_json).to_json_oj};"
    else
      str << "pieces=[];"
      str << "actions=[];"
      str << "from=#{trigger.default_from_number.to_json_oj};"
    end

    if application.tables
      str << "tables=#{application.tables.map(&:as_json).to_json_oj};"
    else
      str << "tables=[];"
    end

    str << "external_services=#{application.external_services.map(&:as_json).to_json_oj};"

    db = application.simulate_triggers_execution_excluding trigger

    str << "db=#{db.to_json_oj};"
    str
  end
end

app/views/message_triggers/_form.haml
%div{'ng-controller' => 'MessageTriggerController', 'ng-init' => message_trigger_to_angular(application, message_trigger)}
  %div{'ng-controller' => 'TriggerController'}
    .row-fluid{dragover: 'dragOverBoard($event)', drop: 'dropOverBoard($event)', dragend: 'dragEnd($event)'}
      .span6
        %label{for: :name} Trigger name
        .row-fluid
          .span11
            %input.span12#name{'ng-model' => '$parent.name', type: :text, name: :name, autofocus: true, placeholder: "Give your trigger a name"}
          .span1
            %input.on-off{'ng-model' => '$parent.enabled', type: :checkbox, name: :enabled, :id => "trigger_enabled"}
            %label{:for => "trigger_enabled"}
        %br
        %br
        %div
          %label{for: :message} When a message like this is received:
          .message-container
            .from
              From:
              .pill.bound{draggable: 'true', dragstart: 'phoneNumberDragStart($event)'}
                {{from}}

            %div
              %patternpad

            .received-at
              %strong Received at:
              .pill.bound{draggable: 'true', dragstart: 'receivedAtDragStart($event)'}
                yyyymmdd
        %br

        = render 'shared/triggers/actions'
      = render 'shared/triggers/tables'

    .row-fluid
      .span6
        %button.btn{'ng-click' => 'save()'} Save
        = link_to "Cancel", application_message_triggers_path(application), class: "btn btn-link"

        - if message_trigger.id
          = icon_link_to :'icf-delete', 'Delete this trigger', "/applications/#{application.id}/message_triggers/#{message_trigger.id}", {method: :delete, confirm: "Are you sure you want to delete this trigger?", class: "pull-right"}
        - else
          = icon_link_to :'icf-delete', 'Delete this trigger', "/applications/#{application.id}/message_triggers/", { class: "pull-right"}

    = render 'shared/triggers/popups'

app/views/message_triggers/edit.haml
%h4 Edit trigger
%p.desc Edit the behaviour of this trigger
%br
= render 'form'

app/views/message_triggers/index.haml
.row-fluid
  .span8
    - simple_list :message_trigger, icon: :'trigger-message', create_path: new_application_message_trigger_path(application) do
      - message_triggers.each do |trigger|
        - simple_list_item trigger.name, edit_application_message_trigger_path(application, trigger)

    - simple_list :periodic_task, icon: :'trigger-date', create_path: new_application_periodic_task_path(application) do
      - periodic_tasks.each do |trigger|
        - simple_list_item trigger.name, edit_application_periodic_task_path(application, trigger)

    - simple_list :external_trigger, icon: :'trigger-external', create_path: new_application_external_trigger_path(application) do
      - external_triggers.each do |trigger|
        - simple_list_item trigger.name, edit_application_external_trigger_path(application, trigger)

    - if validation_triggers.present?
      - simple_list :validation_trigger, icon: :'trigger-external' do
        - validation_triggers.each do |trigger|
          - simple_list_item trigger.field_name, application_validation_trigger_path(application, trigger)

app/views/message_triggers/new.haml
%h4 New Message Trigger
%p.desc Define the behaviour of the trigger by typing an example of a message and indicating the actions that you want to take
%br
= render 'form'